### PR TITLE
Fixed script - run only when closing topic + added ES6 syntax

### PR DESCRIPTION
**Pull request by ChrissP92**
Script was running unnecessary when any user has been adding comment to question. It was weird to see information about giving best answer, before closing topic, when neither Author was a visitor nor subpage was at closing topic state.

Also updated syntax to ES6.

### CODE REVIEW

**Comment by magic96** [comment]
If IIFE is used only for creating new scope - wrap code in brackets instead. It will be a more clear and faster way than calling a function.

**Comment by ChrissP92** [comment]
@magic96 
Do you mean something like below?
`( document ) => { /* code inside IIFE */ } (document)`

**Comment by magic96** [comment]
No, just brackets, without function calling. Something like this:
```js
{
  // code here
}
```
Then, defined variables in this scope won't be available outside it.

**Comment by efiku** [comment]
Please rebase with master

**Pull request closed without merging**
