### PR TITLE
Explicit style for topic's Author nickname

### PR DESCRIPTION
**Pull request by ChrissP92**
**According to:**
- https://trello.com/c/nOyi0R2F/34-wyro-nianie-nicku-u-ytkownika-w-temacie-ktorego-jest-autorem
- http://forum.pasja-informatyki.pl/161642/autor-tematu

, here is a JavaScript with CSS, which will recognize and make the style of topic's Author nickname a little bit different to other Users who participate in topic's discussion.

### CODE REVIEW

**Comment by awaluk** [comment]
In my opinion highlighting nickname is good, but during tests I saw some alerts "Adding comment" when I add comment to answer/question.
Additionally if I add a new answer, nickname is not highlighted. You can fix this problems? I know that when add a new answer/comment don't work other functions, for example vote on comments or syntax highlighting, but might you be able to do it well?

**Comment by ChrissP92** [comment]
**@awaluk** I fixed problem you mentioned. I also removed `alert()`, `console.log()`s and did some cleanup.
Now, it should work fine.

**Comment by awaluk** [comment]
Yes, now it's very good for me :)

**Comment by Comandeer** [comment]
There is one, small issue with your PR – look at [the produced diff](https://github.com/CodersCommunity/forum.pasja-informatyki.local/pull/44/files). TBH is totally useless as 98% of changes is not connected with the added feature at all.

If you want to do cleanup, make a separate PR with **just** cleanup. At the meantime you can create the PR with the new feature and after accepting and merging cleanup to the master, just rebase your changes.

**Comment by ChrissP92** [comment]
@Comandeer, the reason why 98% of file is reformated is I wanted to reformat only my code, but did CTRL + A and used autoformat in WebStorm. Then i forgot that actually all code is reformatted, so I pushed like that. I am sorry.

Do you know some painless way to revert that changes without touching my code?

**Comment by Comandeer** [comment]
Try rebasing (but I'm sure if it would be totally painless ;)).

**Comment by ChrissP92** [comment]
Refreshed branch and PR: https://github.com/CodersCommunity/forum.pasja-informatyki.local/pull/45

**Pull request closed without merging**
